name: blt
description: The BLT-Flutter App

version: 1.0.3+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  google_fonts: ">=3.0.1 <5.0.0"
  http: ^0.13.1
  image_picker: ^1.0.4
  receive_sharing_intent:
    git:
      url: https://github.com/Thogsit/receive_sharing_intent
  shared_preferences: ^2.0.5
  flutter_svg: ">=1.0.3 <3.0.0"
  flutter_riverpod: ^1.0.3
  intl: ">=0.17.0 <0.19.0"
  flutter_secure_storage: ">=5.0.2 <9.0.0"
  smooth_page_indicator: ^1.0.0+2
  pasteboard: ^0.2.0
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  flutter_inappwebview: ^5.7.2+3
  font_awesome_flutter: ^10.4.0
  sentry_flutter: ^7.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_launcher_icons: ">=0.9.0 <0.13.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login_signup/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_large_icon.png"
  remove_alpha_ios: true
