name: bugheist
description: The Bugheist App

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  image_picker: ^0.7.4
  provider: ^5.0.0
  receive_sharing_intent: ^1.4.5
  shared_preferences: ^2.0.5
  #flutter_lints: ^1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login_signup/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
